# Generated by Django 4.1.1 on 2022-09-21 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabezaGanado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('peso_kg', models.FloatField()),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_finca', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('direccion_encargado', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGanado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('direccion', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.tipousuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('monto_venta', models.FloatField()),
                ('cabeza_ganado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cabezaganado')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.finca')),
            ],
        ),
        migrations.CreateModel(
            name='GanadoFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.IntegerField()),
                ('potrero', models.IntegerField()),
                ('cabeza_ganado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cabezaganado')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.finca')),
            ],
        ),
        migrations.AddField(
            model_name='finca',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
        ),
        migrations.AddField(
            model_name='cabezaganado',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.tipoganado'),
        ),
        migrations.AddConstraint(
            model_name='ganadofinca',
            constraint=models.UniqueConstraint(fields=('cabeza_ganado', 'finca'), name='pk_compuesta'),
        ),
    ]
