# Generated by Django 4.1.1 on 2022-09-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazaGanado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_raza', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='cabezaganado',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.razaganado'),
        ),
    ]
